# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

variables:
  CI: true
  npm_config_cache: $(Pipeline.Workspace)/.npm

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: npmAuthenticate@0
  inputs:
    workingFile: .npmrc
    customEndpoint: 'my-npm-connection'
    
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

# - task: CacheBeta@1
#   inputs:
#     key: npm | $(Agent.OS)
#     path: $(npm_config_cache)
#   displayName: 'Cache Npm'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm pack
  displayName: 'Package for release'

- bash: |
    v=`node -p "const p = require('./package.json'); p.version;"`
    echo "##vso[task.setvariable variable=packageVersion]$v"

- task: CopyFiles@2
  inputs:
      contents: '*.tgz'
      targetFolder: $(Build.ArtifactStagingDirectory)
  displayName: 'Copy archives to artifacts staging directory'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: 'package.json' 
    targetFolder: $(Build.ArtifactStagingDirectory)/npm
  displayName: 'Copy package.json'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/npm'
    artifactName: npm
  displayName: 'Publish npm artifact'


- script: |
    npm config set //registry.npmjs.org/:_authToken=${NPMTOKEN}
    npm config set scope "@juliakm"
    npm config list
    npm --version
    #npm version minor --force
    #npm publish --access public

- powershell: |
   git --version
   New-Item -Path "$(System.DefaultWorkingDirectory)" -Name "testfile1.txt" -ItemType "file" -Value "This is a text string."
   Write-Host "new file created, now adding file to git"
   git add -A
   Write-Host "setup author info"
   git config user.email jukullam@microsoft.com
   git config user.name "Julia Kulla-Mader"
   Write-Host "git commit with message"
   git commit -a -m "Test Commit from Azure DevOps"
   Write-Host "git push"
   git push


