# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

variables:
  CI: true
  npm_config_cache: $(Pipeline.Workspace)/.npm

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true
  clean: true

# - task: CmdLine@2
#   inputs:
#     script: |
#       git config --global user.email "jukullam@microsoft.com"
#       git config --global user.name "Azure Pipeline"
#       git pull git@github.com:juliakm/tiny.git master
    
- task: npmAuthenticate@0
  inputs:
    workingFile: .npmrc
    customEndpoint: 'my-npm-connection'
    
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

# - task: CacheBeta@1
#   inputs:
#     key: npm | $(Agent.OS)
#     path: $(npm_config_cache)
#   displayName: 'Cache Npm'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm pack
  displayName: 'Package for release'

- bash: |
    v=`node -p "const p = require('./package.json'); p.version;"`
    echo "##vso[task.setvariable variable=packageVersion]$v"
- task: CopyFiles@2
  inputs:
      contents: '*.tgz'
      targetFolder: $(Build.ArtifactStagingDirectory)
  displayName: 'Copy archives to artifacts staging directory'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: 'package.json' 
    targetFolder: $(Build.ArtifactStagingDirectory)/npm
  displayName: 'Copy package.json'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/npm'
    artifactName: npm
  displayName: 'Publish npm artifact'


- script: |
    npm config set //registry.npmjs.org/:_authToken=${NPMTOKEN}
    npm config set scope "@juliakm"
    npm config list
    npm --version
    npm version patch --force
    npm publish --access public
- task: CmdLine@2
  inputs:
    script: |
      git config --global user.email "jukullam@microsoft.com"
      git config --global user.name "Azure Pipeline"
      git add package.json
      git commit -a -m "Test Commit from Azure DevOps"
      git push -u origin HEAD:master
     # git remote rm origin
     # git remote add origin git@github.com:juliakm/tiny.git
     # git push -u origin HEAD:master
